Update java-maven-api-master.yml

diff --git a/.github/workflows/java-maven-api-master.yml b/.github/workflows/java-maven-api-master.yml
--- a/.github/workflows/java-maven-api-master.yml
+++ b/.github/workflows/java-maven-api-master.yml
@@ -11,6 +11,7 @@ on:
 
 jobs:
   build:
+    name: Build
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
@@ -19,9 +20,10 @@ jobs:
       with:
         java-version: 1.11
     - name: Build with Maven
-      run: mvn -B package --file pom.xml
-  test:
+      run: mvn -B compile --file pom.xml
+  unit-test:
     name: Unit Test
+    needs: [build]
     runs-on: ubuntu-18.04
     steps:
     - uses: actions/checkout@v1
@@ -29,11 +31,55 @@ jobs:
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
-    - name: Maven Verify
+    - name: Unit Test
       run: mvn -B clean verify
-  publish:
-    name: Publish
+  contract-test:
+    name: Contract Test
+    needs: [build]
+    runs-on: ubuntu-16.04
+    steps:
+    - uses: actions/checkout@v1
+    - name: Set up JDK 11
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.11
+    - name: API Contract Testing
+      run: |
+        mvn clean install
+        sudo apt-get install libxml2-utils
+        #VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:execxml)
+        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
+        java -jar target/calculator-api-$VERSION.jar &
+        PID=$!
+        sleep 20
+        result=$(curl -s http://localhost:7111/addition/1/2/3 | jq .result)
+        if [ $result -eq 6 ]; then
+          echo "API Contract Testing is successful"
+        else
+          echo "API Contract Testing failed"
+          exit 1
+        fi
+        kill -9 $PID > /dev/null
+  sonar:
+    name: Static Code Analysis
+    needs: [build]
     runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v1
+      - name: Set up JDK 11
+        uses: actions/setup-java@v1
+        with:
+          java-version: 11.0.4
+      - name: SonarCloud Scan
+        run: mvn -B clean verify -Psonar -Dsonar.login=$SONAR_TOKEN
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  publish:
+    name: Publish    
+    runs-on: ubuntu-latest
+    needs: [unit-test,contract-test,sonar]   
 
     steps:
     - uses: actions/checkout@v1
@@ -47,4 +93,93 @@ jobs:
       run: |
         mkdir -p ~/.m2
         echo "<settings><servers><server><id>github</id><username>govindarajanv</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
-        mvn deploy
+        mvn clean deploy
+    - name: Build Container Image
+      run: |
+        sudo apt-get install libxml2-utils
+        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
+        docker build -t govindarajanv/calculator-api:$VERSION .
+        docker build -t govindarajanv/calculator-api:latest .
+        docker images
+    - name: Test Image
+      run: |
+        docker-compose up -d
+        docker ps
+        sleep 60
+        docker ps
+        result=$(docker inspect --format='{{json .State.Health}}' calculator| jq ."Status")
+        if [ $result != "\"healthy\"" ]; then exit 1; fi        
+    - name: Shut down the service
+      run: docker-compose down
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    - name: Publish the image
+      run: |
+        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
+        docker push govindarajanv/calculator-api:$VERSION 
+        docker push govindarajanv/calculator-api:latest
+    - name: Share artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: my-artifact
+        path: target/*
+        retention-days: 5
+  integration-test:
+    name: API Integration Testing
+    runs-on: ubuntu-latest
+    needs: [publish]
+    steps:
+    - uses: actions/checkout@v1
+    - name: Get PWD
+      run: |
+        echo $pwd
+    - name: Set up JDK 1.11
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.11
+    - name: API Contract Testing
+      run: |
+        echo "Integration Testing is Stubbed"
+  deploy:
+    name: Deploy/Release to production
+    needs: [integration-test]
+    runs-on: ubuntu-latest
+    steps:
+     - uses: actions/checkout@v1
+     - name: Download a single artifact
+       uses: actions/download-artifact@v2
+       with:
+         name: my-artifact
+         path: target/
+     - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
+       run: |
+          sudo apt-get install libxml2-utils
+          docker login --username=$(heroku whoami) --password=$(heroku auth:token) registry.heroku.com
+          VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
+          docker build -t registry.heroku.com/calculator-java-maven-service/web:$VERSION --build-arg value=$VERSION . -f Dockerfile
+          docker build -t registry.heroku.com/calculator-java-maven-service/web:latest --build-arg value=$VERSION . -f Dockerfile
+          docker push registry.heroku.com/calculator-java-maven-service/web:latest
+          heroku container:login
+          app_version=$(heroku apps:info calculator-java-maven-service -j | jq ."dynos[0].release.version")
+          echo "Current App version is $app_version"
+          heroku container:rm web -a calculator-java-maven-service
+          heroku container:release web -a calculator-java-maven-service
+          app_version=$(heroku apps:info calculator-java-maven-service -j | jq ."dynos[0].release.version")
+          echo "Released App version is $app_version"
+       env:
+          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
+          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
+     - name: Post Deployment Check
+       run: |
+        sleep 60
+        result=$(curl -s https://calculator-java-maven-service.herokuapp.com/addition/1/2/3 | jq .result)
+        if [ $result -eq 6 ]; then
+          echo "Application is successfully deployed in production"
+        else
+          echo "Prod deployment failed"
+          exit 1
+        fi    
